### ISSUE TITLE
Add State QRIS

### ISSUE THREAD

**Issue by danxoneil** [smartchicago/chicago-early-learning#134]
Coming in 2014.

**Comment by danxoneil** [comment]
QRIS data is here: https://dl.dropboxusercontent.com/u/97776980/082714%20Chicago%20Programs%20and%20ExceleRate%20Ratings.xlsx

**Comment by smarziano** [comment]
We will be receiving an updated dataset from INCCRRA by the end of next week. Here is some updated information about these ratings according to Gail Nelson, QRIS Policy Director. Our questions about the data included 1) why there were not Bronze ratings?, 2) how to describe locations that have not been rated.
- Sites that do not have a rating would be listed as "Licensed."  "That is Level 1 of the QRIS.  I would not suggest "not rated" because that implies they will be -- but the fact is that they will not be rated unless they choose to apply for a rating.  So "Licensed" is the clearest way to describe them."
- "There is also a "Bronze" Circle of Quality -- that is Level 2 of the QRIS.  Bronze recognizes completion of a robust series of trainings by the program administrator and a proportion of the teachers at the site -- sort of a "fill your toolbox" series that builds content knowledge for each of the ExceleRate standards.  I believe a few sites in Chicago have achieved this rating."
- "As for the schools, at this time I believe we have ratings for all of the CPS schools, so none should be "not rated."

**Comment by smarziano** [comment]
We have received an updated document with rating from INCCRRA. Here is the spreadsheet: https://www.dropbox.com/s/br6xh20kk3djr16/070215%20Chicago%20Programs%20and%20ExceleRate%20Ratings.xlsx?dl=0

@frankwiles Can you please upload this data to the portal? For any sites that do not have a rating, please list them as "Licensed."

**Comment by frankwiles** [comment]
Sure I'll get this loaded up tomorrow.

**Comment by frankwiles** [comment]
Ok we've got some small problems with this data.  The names and addresses don't always match up. For example current DB has 3 'Carole Robertson Center for Learning's Excel file has only 2 'Carole Robertson Ctr for Learning'.  Thought about matching on address, but that's going to be a bit "loose" as well with 'Avenue vs Ave' type differences.  

I'm going to load things up as best I can, but a human is going to need to go through and verify this info.  I'll add the 'rating' to the main admin listing screen on locations to make that work easier.

**Comment by frankwiles** [comment]
Ok this is loaded on staging and production now.  I'll email you the list of locations that did not match (for various reasons) about 138 of them out of the 400+ for someone to review.
