### ISSUE TITLE
Unclear what difference is between "School" and "Center" for map symbology

### ISSUE THREAD

**Issue by shua123** [smartchicago/chicago-early-learning#370]
What is the difference between "School" and "Center" in the map symbology? How are the programs classified?

**Comment by smarziano** [comment]
@shua123,
I replicated what you did. When you chose a specific community area, the map also displays nearby locations. For example, when looking at Head Starts in Albany Park, the Korean American Community Service Center is also displayed. This location is tagged as being part of the Irving Park neighborhood.

I am closing this issue for now since this function provides users nearby options to enroll their child in an early learning program.
