### ISSUE TITLE
"Directions" use current location or search query

### ISSUE THREAD

**Issue by smarziano** [smartchicago/chicago-early-learning#521]
The "Directions" feature uses current location. @theandrewbriggs, we talked about having this use the address already used in search, but does that make things overly complicated? First, users can search in multiple ways (not by address), and then we would have to store the address or search result they used to find directions. This is something we should think about, but is a low priority at this time.

**Comment by smarziano** [comment]
This button should use the address or location information in the search query and then find directions from that.

**Comment by theandrewbriggs** [comment]
@smarziano Because of how we reconfigured the site, I don't think this feature really makes sense any more, as we're not linking to directions directly from the map. The only place this could work is on the mobile map view, which uses the user's current location for directions, but I think this should behave consistent with the directions link on the center detail page.

**Comment by smarziano** [comment]
I agree with your last comment, @theandrewbriggs. I am closing this issue.
