### ISSUE TITLE
Update design of the center detail page

### ISSUE THREAD

**Issue by smarziano** [smartchicago/chicago-early-learning#823]
As part of our redesign milestone, @amynicole & @jenmakes created this design of a center detail page:
![location page](https://user-images.githubusercontent.com/5550969/27942402-2c8c0744-629c-11e7-95df-ee1e516b7ccd.png)

In general, I like how our page currently looks but I like the general refresh and update being made in this design. Here are my notes:
- I don't like the inconsistency of fonts that are being used for the description and note fields ("Note: Availability and placement..." and "If you are interested in enrolling your child in this home visiting...")
- I am not a fan of the bullet points being used
- I am afraid of using the checkmark symbol for "Slots Available" because I think it would mean that we would use "X" for "Limited Availability" which I am worried would confused parents that they can't apply to that location
- I like the ordering of the "Compare and Apply," "Share" and "Directions" but think we should keep some iconography
- Let's separate Compare and Apply into two different buttons based on issue #819, one button would encourage users to add to their compare & apply list and the other would be to apply to that location

Please also take the addition of content or "tooltips" seen in this issue https://github.com/smartchicago/chicago-early-learning/issues/683#issuecomment-313583226 into consideration.

**Comment by jenmakes** [comment]
@smarziano  all of these text styles are consistent with styles used elsewhere on the site. Font styles are differentiated to provide clear hierarchy. Bullet color can be muted more — I started using a grey on other pages since I read the note. 

In regards to the check vs 'x' — I am using the symbols currently being used on the site. I find the icons generally confusing if an 'x' means limited — I thought that meant unavailable. What are the different statuses that would be relevant here to indicate? Just the two or more?

**Comment by smarziano** [comment]
Availability can only be one of two things: Seats Available or Limited Availability
Since there is a verification process after a child is placed that means that there are a few more steps before a seat is actually confirmed. Therefore, we never say that there are seats unavailable, we always say seats are limited. 

I am understanding what you are saying about the font styles. Maybe it's just that I just don't like this font. Is it Minion Pro Regular? If so, let's keep it since it's part of the communications firm style guide.

**Comment by jenmakes** [comment]
After reviewing icons with Amy for a bit, we both think we should scrap the use of an icon in this section (for both the location info and location compare pages) because it is semiotically confusing no matter how we look at it. Using text would be more effective for limited availability.

Here is the page:  https://cl.ly/1x0i2Q3N2U0O

Here is a snapshot of it in use on a compare tile: https://cl.ly/3q2k2G0A0W2h

Text was in the guidelines and ties back to the blog. Didn't touch it :)

**Comment by smarziano** [comment]
I believe this page may be adjusted based on some of the updates we make to the user sessions (cc: @amynicole). 

For the July 31 deadline, I want to take a step back and stay closer to our current design as we work out what a broader change might be on this page. Let's do the following to this page:
- Remove the bullet points
- Do not use a check mark next to "Slots Available"
- Use check mark or X like it currently exists on the website, but in the updated styling:
<img width="961" alt="screen shot 2017-07-16 at 11 53 08 pm" src="https://user-images.githubusercontent.com/5550969/28256687-f3a05744-6a81-11e7-8064-5625187ed25a.png">

- Separate the Compare and Apply buttons (see issue #819)
- Let's remove the italics and only use it for notes like "Ages 3 - 5: If your child is 3 or 4 years old prior to September 1, 2017, your child will be eligible for preschool programs. Click here to fill out an application for two preferred sites or call the Chicago Early Learning Hotline at (312) 229-1690 for assistance." or "Note: Availability and placement are subject to eligibility."

**Comment by jenmakes** [comment]
Good Morning @smarziano, I hope you are having a good trip!

I went ahead and updated the styling on the Location information page. I removed the bullets, removed the italics on the bullets and made the notes italic. In regards to the icons, I re-added the 'x' next to "Ages 0-3" - but I made it yellow since the 'x' vs 'check' alone doesn't really signify anything clearly by themselves. We could use color as a visual device here, green is positively available - yellow signifies potentially available or maybe not that many seats. I do think the added "(limited availability)" text next to it really clarifies what the bullet is really trying to say. You should keep the green check mark next to 'slots available', because without it - availability doesn't feel visually available compared to the Ages Served section above. Your call in the end, but I'm worried you are not calling that note out enough. 

update: https://cl.ly/273V2z2t1r2c

**Comment by amynicole** [comment]
![location page v2](https://user-images.githubusercontent.com/7504439/28447776-a9c27b24-6d98-11e7-97f6-7a05641d52e4.png)

This version has definitions for accreditation and quality rating. They are truncated versions of what is shown on the programs page. The other definitions are under tooltips.

**Comment by smarziano** [comment]
This issue is completed. Closing!
