### ISSUE TITLE
Design tweaks to homepage

### ISSUE THREAD

**Issue by smarziano** [smartchicago/chicago-early-learning#877]
@amynicole and I have identified some design tweaks that need to be made to the homepage.

- [x] Confetti asset needs to be scaled down to match closer to the design seen in issue #825, currently, it is zoomed to the point where some of shapes are not fitting in that block as they should
- [x] Update "Explore our early learning programs!" headline text from 24px to 36px
- [x] Update "What is the preschool application process?" headline text from 24px to 36px
- [x] Increase vertical padding for "Explore our early learning programs!" and "What is the preschool application process?" sections
- [x] More padding between "Latest News" headline and news blurbs
- [ ] Adjust the "Latest News" blurbs to line up more
- [x] Add the clock symbol and length of video under the embed as seen in issue #825 
- [x] Quote from mayor should be: 22 px tall, 20 px line height
- [x] Hero image looks tight... meaning that there is not as much space at the top of the little girl's head

**Comment by theandrewbriggs** [comment]
So for the aligning News blocks, this is the best I can do, having the preview blocks fade out at the same heights:
![screen shot 2017-09-24 at 15 59 34 pm](https://user-images.githubusercontent.com/3439795/30786819-75581a42-a141-11e7-968b-37fe5a22b032.png)

However, because the headlines are gonna wrap, we don't really have any control over what happens at different screen sizes:

![screen shot 2017-09-24 at 16 00 57 pm](https://user-images.githubusercontent.com/3439795/30786828-96de34e4-a141-11e7-98e6-f50e2a1a09a5.png)

**Comment by smarziano** [comment]
@theandrewbriggs I am not sure if I like this fade out and it's not really solving the problem. Since there isn't a great solution for this, let's change this back to how it was before (no fade out). It's not a huge issue that it's not completely aligned and maybe when we have more content we will think of a better solution. 

Also, there's a bug for the fade out on Safari:
<img width="894" alt="screen shot 2017-09-24 at 5 06 01 pm" src="https://user-images.githubusercontent.com/5550969/30787279-aac5c2fc-a14a-11e7-8ff1-96bcf0ba720e.png">

**Comment by theandrewbriggs** [comment]
This last bug has been fixed, everything else is live on production.
