### ISSUE TITLE
Mobile: Make it is easier to close filters pop-up

### ISSUE THREAD

**Issue by smarziano** [smartchicago/chicago-early-learning#904]
Related to issue #889. Currently, it is a little cumbersome to close the filters pop-up. It's not very intuitive how you get out of the filters pop-up once you choose your options. I want to add an "Apply filters" button or an "X" to exit this pop-up, or something similar.

**Comment by theandrewbriggs** [comment]
@smarziano Because space is at a premium in the filters pane, here's my solution for this: 

Instead of putting the clear filter button in the filter pane, I'm gonna make that a close button, and then make "refine your search" a button and stick "Reset Filters" next to it.

How it is now:
![screen shot 2017-10-01 at 14 58 52 pm](https://user-images.githubusercontent.com/3439795/31058499-4a85a9b4-a6ba-11e7-8789-087038213fd0.png)

What it WILL look like:
![screen shot 2017-10-01 at 14 59 30 pm](https://user-images.githubusercontent.com/3439795/31058504-55addad2-a6ba-11e7-98ab-cb62c7e5cdd1.png)
![screen shot 2017-10-01 at 15 03 23 pm](https://user-images.githubusercontent.com/3439795/31058505-55ae80a4-a6ba-11e7-9dfb-85224dfd8dc6.png)

**Comment by theandrewbriggs** [comment]
This is live on production.

**Comment by smarziano** [comment]
@theandrewbriggs I like this solution, but with the buttons stacked it is taking a lot of room from the left panel, especially with the "Compare sites" button appearing at the top:
<img width="1275" alt="screen shot 2017-10-02 at 9 14 34 am" src="https://user-images.githubusercontent.com/5550969/31081674-395268a6-a752-11e7-8060-33a8b4c8747e.png">

I think the side-by-side buttons will be an improvement.

**Question:** When clicking "Reset Filters," does that also clear the age parameters a parent has already set or just the additional filters they might have added after clicking "Refine your search?"

**Comment by smarziano** [comment]
@theandrewbriggs I like the side-by-side buttons, but I think they should have the same styling that currently exists for buttons. Therefore, the "Refine your search" button should be orange and the "Reset Filters" button should be grey like what exists on production.

**Comment by smarziano** [comment]
After our recent discussion via Slack, I understand that my request would make this look very busy. I like the current format and so I am going to say that this is "Waiting on merge."
